### ISSUE TITLE
The actual Firebase class seems to be missing?

### ISSUE THREAD

**Issue by koppelaar** [ktamas77/firebase-php#24] opened 2015-04-03 07:03 UTC
I'm probably an idiot for asking this, but when running the example I get this:

*Fatal error: Class 'Firebase' not found in (.....)/firebase-php/index.php on line 8*

The code I'm using is this:

    <?php
    require 'autoload.php';
    
    const DEFAULT_URL = 'https://xxxx.firebaseio.com';
    const DEFAULT_TOKEN = 'yyyy';
    const DEFAULT_PATH = '';
    
    $firebase = new Firebase(DEFAULT_URL, DEFAULT_TOKEN);
    
    $test = array(
        "foo" => "bar",
        "i_love" => "lamp",
        "id" => 42
    );
    
    $dateTime = new DateTime();
    
    $firebase->set(DEFAULT_PATH . '/' . $dateTime->format('c'), $test);

    ?>

**Comment by jjok** [comment] 2015-05-05 14:57
It seems to be called `FirebaseLib` now.

**Comment by jjok** [comment] 2015-05-05 14:57
The README needs updating.

**Comment by jjok** [comment] 2015-05-05 15:38
Duplicate of #22.

**Comment by ktamas77** [comment] 2015-05-08 01:59
Readme is updated, it should be straightforward now. Thank you for your note.

**Closed by ktamas77** 2015-05-08 01:59 UTC
